### ISSUE TITLE
Outdates URL

### ISSUE THREAD

**Issue by ItsCOMMANDer** [MESYETI/cc-skinfetch#1]
The URL `http://classicube.s3.amazonaws.com/skin/NAME.png` doesnt work anymore, but i have found, that `https://cdn.classicube.net/skin/NAME.png` does. its a simple fix but idk how to make a pull request.

**Comment by MESYETI** [comment]
this project is like 90 million years old i wouldn't bother fixing it

**Comment by ItsCOMMANDer** [comment]
> this project is like 90 million years old i wouldn't bother fixing it

Fine, i'll do it myself
